Fixed typos and updated .gitignore
EpiCanard/ChopTree pull request #1
Opened 2020-10-03 13:42 UTC by abhyuday10

I have fixed the spelling of the resources folder which maven uses to build the jar plugin.
I have also updated the gitignore file to ignore files used by maven which should not be committed to to the repository.

2020-10-03 18:52 UTC, EpiCanard requested changes
You renamed the folder `ressources` into `resources` but you didn't changed the path inside the pom.xml.
So the resources files are no longer inside the jar.

2020-10-03 18:52 UTC, EpiCanard commented on .gitignore
> +.mvn/wrapper/maven-wrapper.jar
These lines are already present just above.
Except for `.mvn/wrapper/maven-wrapper.jar` but you can ignore it I don't use it.

2020-10-03 20:37 UTC, abhyuday10 commented
Ahh apologies, I added the wrong code block in gitignore. I also missed the reference in pom.xml, I've fixed both now.

2020-10-04 11:59 UTC, EpiCanard approved these changes

2020-10-04 11:59 UTC, merged